Post.create(body: 'Hello, this is my first post!')
Post.create(body: 'Hi, , this is my second post! ')
Post.create(body: "You're welcome")
Post.create(body: 'How was your day?')
Post.create(body: 'Happy to see you again')
